export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

//USER ACTIONS
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';


//ADVERT ACTIONS
export const SHOW_SINGLE_ADVERT = "SHOW_SINGLE_ADVERT"
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_ADVERT_FORM_VALUES = 'CLEAR_ADVERT_FORM_VALUES';

export const CREATE_ADVERT_BEGIN = 'CREATE_ADVERT_BEGIN';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const CREATE_ADVERT_ERROR = 'CREATE_ADVERT_ERROR';

export const GET_ADVERT_BEGIN = 'GET_ADVERT_BEGIN';
export const GET_ADVERT_SUCCESS = 'GET_ADVERT_SUCCESS';

export const SET_EDIT_ADVERT = 'SET_EDIT_ADVERT';

export const GET_USER_ADVERT_BEGIN = 'GET_USER_ADVERT_BEGIN';
export const GET_USER_ADVERT_SUCCESS = 'GET_USER_ADVERT_SUCCESS'
export const GET_USER_ADVERT_ERROR = 'GET_USER_ADVERT_ERROR'

export const GET_OTHER_USER_ADVERT_BEGIN = 'GET_OTHER_USER_ADVERT_BEGIN';
export const GET_OTHER_USER_ADVERT_SUCCESS = 'GET_OTHER_USER_ADVERT_SUCCESS'
export const GET_OTHER_USER_ADVERT_ERROR = 'GET_OTHER_USER_ADVERT_ERROR'

export const EDIT_ADVERT_BEGIN = 'EDIT_ADVERT_BEGIN';
export const EDIT_ADVERT_SUCCESS = 'EDIT_ADVERT_SUCCESS';
export const EDIT_ADVERT_ERROR = 'EDIT_ADVERT_ERROR';

export const DELETE_ADVERT_BEGIN = 'DELETE_ADVERT_BEGIN';
export const DELETE_ADVERT_SUCCESS = 'DELETE_SUCCESS_SUCCESS';
export const DELETE_ADVERT_ERROR = 'DELETE_SUCCESS_ERROR';

export const DELETE_ADMIN_ADVERT_BEGIN = 'DELETE_ADMIN_ADVERT_BEGIN'
export const DELETE_ADMIN_ADVERT_SUCCESS = 'DELETE_ADMIN_ADVERT_SUCCESS'


export const CHANGE_PAGE = 'CHANGE_PAGE'
export const SET_IMAGE_LIST = "SET_IMAGE_LIST"
export const UPLOAD_IMAGE_LIST_BEGIN = "UPLOAD_IMAGE_LIST_BEGIN"
export const UPLOAD_IMAGE_LIST_SUCCESS = "UPLOAD_IMAGE_LIST_SUCCESS"
export const UPLOAD_IMAGE_LIST_ERROR = "UPLOAD_IMAGE_LIST_ERROR"
export const DELETE_IMAGE_BEGIN = "DELETE_IMAGE_BEGIN"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_ERROR = "DELETE_IMAGE_ERROR"


//BANKER ACTIONS
export const CLEAR_BANKER_FORM_VALUES = 'CLEAR_BANKER_FORM_VALUES';

export const CREATE_BANKER_BEGIN = 'CREATE_BANKER_BEGIN';
export const CREATE_BANKER_SUCCESS = 'CREATE_BANKER_SUCCESS';
export const CREATE_BANKER_ERROR = 'CREATE_BANKER_ERROR';

export const GET_BANKER_BEGIN = 'GET_BANKER_BEGIN';
export const GET_BANKER_SUCCESS = 'GET_BANKER_SUCCESS';

export const SET_EDIT_BANKER = 'SET_EDIT_BANKER';
export const DELETE_BANKER_BEGIN = 'DELETE_BANKER_BEGIN';

export const EDIT_BANKER_BEGIN = 'EDIT_BANKER_BEGIN';
export const EDIT_BANKER_SUCCESS = 'EDIT_BANKER_SUCCESS';
export const EDIT_BANKER_ERROR = 'EDIT_BANKER_ERROR';

//AGENT ACTIONS
export const CLEAR_AGENT_FORM_VALUES = 'CLEAR_AGENT_FORM_VALUES';

export const CREATE_AGENT_BEGIN = 'CREATE_AGENT_BEGIN';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_ERROR = 'CREATE_AGENT_ERROR';

export const GET_AGENT_BEGIN = 'GET_AGENT_BEGIN';
export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS';

export const SET_EDIT_AGENT = 'SET_EDIT_AGENT';
export const DELETE_AGENT_BEGIN = 'DELETE_AGENT_BEGIN';

export const EDIT_AGENT_BEGIN = 'EDIT_AGENT_BEGIN';
export const EDIT_AGENT_SUCCESS = 'EDIT_AGENT_SUCCESS';
export const EDIT_AGENT_ERROR = 'EDIT_AGENT_ERROR';

//HDB TRANSACTION ACTIONS
export const SEARCH_TRANSACTION_BEGIN = 'SEARCH_TRANSACTION_BEGIN';
export const SEARCH_TRANSACTION_SUCCESS = 'SEARCH_TRANSACTION_SUCCESS';
export const CLEAR_SEARCH_FORM_VALUES = 'CLEAR_SEARCH_FORM_VALUES';

//MESSAGING ACTIONS
export const GET_CONVERSATIONS_BEGIN = 'GET_CONVERSATIONS_BEGIN';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';

