export const START_APP_SUCCESS = 'START_APP_SUCCESS'

//USER ACTIONS
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

//ADVERT ACTIONS
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const GET_ADVERT_BEGIN = 'GET_ADVERT_BEGIN';
export const GET_ADVERT_SUCCESS = 'GET_ADVERT_SUCCESS';
export const GET_USER_ADVERT_BEGIN = 'GET_USER_ADVERT_BEGIN';
export const GET_USER_ADVERT_SUCCESS = 'GET_USER_ADVERT_SUCCESS'
export const GET_USER_ADVERT_ERROR = 'GET_USER_ADVERT_ERROR'
export const EDIT_ADVERT_SUCCESS = 'EDIT_ADVERT_SUCCESS';
export const SET_AREA = 'SET_AREA'
export const SET_UNIT_TYPE = 'SET_UNIT_TYPE'
export const DELETE_ADVERT_SUCCESS = 'DELETE_SUCCESS_SUCCESS';
export const UPLOAD_IMAGE_LIST_SUCCESS = "UPLOAD_IMAGE_LIST_SUCCESS"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"

//BANKER ACTIONS
export const GET_BANKER_SUCCESS = 'GET_BANKER_SUCCESS';

//AGENT ACTIONS
export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS';

//HDB TRANSACTION ACTIONS
export const SEARCH_TRANSACTION_BEGIN = 'SEARCH_TRANSACTION_BEGIN';
export const SEARCH_TRANSACTION_SUCCESS = 'SEARCH_TRANSACTION_SUCCESS';


